### ISSUE TITLE
'tweet your review time' error

### ISSUE THREAD

**Issue by bizz84** [nthegedus/ReviewTime#1]
Hi,

While running on iOS 9 I get the following error after selecting one of my (four) Twitter accounts:
NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)

This error goes away by adding NSAllowsArbitraryLoads to the info.plist file (see [this link](http://www.fiveminutewatchkit.com/blog/2015/6/9/how-to-disable-app-transport-security) for an explanation), however by making this change the method tweetReviewTimeWithHashtag() ends up being called recursively and the Twitter compose screen is never presented.

I believe this code logic should be revisited.

Andrea

**Comment by nthegedus** [comment]
Hi bizz84, thanks to open this issue. 

It's now fixed!

There is a great video in WWDC explain about ATS https://developer.apple.com/videos/wwdc/2015/?id=711
